language: node_js
sudo: false
node_js:
  - 10.15.3

branches:
  only:
    - master

script:
  - echo 0

after_success:
  - $(which npm) install -g firebase-tools@latest
  - firebase use firebase-angular-material
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then firebase deploy --non-interactive --token $FIREBASE_TOKEN; fi
